from __future__ import annotations

import os

import httpx

HF_URL = "https://api-inference.huggingface.co/models/meta-llama/Llama-2-7b-chat-hf"


async def ask_huggingface(question: str, context: dict) -> str:
    token = os.getenv("HUGGINGFACE_API_KEY", "")
    if not token:
        return "HUGGINGFACE_API_KEY is not configured on the backend environment."

    prompt = (
        "You are a healthcare EDI assistant. Answer only using X12 HIPAA 5010 context."
        f"\nContext:\n{context}\n\nQuestion:\n{question}\n\n"
        "Give an accurate, practical answer with specific segment and element references when possible."
    )

    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 450,
            "temperature": 0.2,
            "return_full_text": False,
        },
    }

    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }

    async with httpx.AsyncClient(timeout=60) as client:
        try:
            response = await client.post(HF_URL, json=payload, headers=headers)
            response.raise_for_status()
            data = response.json()
        except Exception as exc:
            return f"Hugging Face API error: {exc}"

    if isinstance(data, list) and data:
        first = data[0]
        if isinstance(first, dict) and "generated_text" in first:
            return str(first["generated_text"]).strip()

    return "No response generated by model."

