"""
ValidEDI LLM Demo Test
======================

Quick demo showing LLM functionality with a mock LLM.
Run this to see how the LLM integration works without needing real API keys.
"""

from validedi import parse, validate
from validedi.llm import explain, ask_followup, LLMExplainer


def mock_llm(prompt: str) -> str:
    """
    Mock LLM for testing - returns a realistic response.
    In production, replace this with your real LLM.
    """
    if "follow-up" in prompt.lower() or "question" in prompt.lower():
        # Q&A response
        return """Based on the EDI file data, the total billed amount is $4,250.00 
across 3 claims. This includes services for pneumonia treatment, routine checkup, 
and physical therapy. All claims are from March 2024."""
    else:
        # Explanation response
        return """
OVERVIEW
--------
This is a Professional Health Care Claim (837P) submission from ABC Medical Group 
to BlueCross BlueShield. It contains 3 outpatient claims totaling $4,250.00 for 
services rendered in March 2024.

KEY PARTIES
-----------
• Submitter: ABC Medical Group (ID: 12345)
• Billing Provider: Dr. Jane Smith (NPI: 1234567890)
• Payer: BlueCross BlueShield (ID: BCBS001)

FINANCIAL SUMMARY
-----------------
• Total Claims: 3
• Total Billed: $4,250.00
• Service Period: March 1-15, 2024
• Submission Date: March 20, 2024

VALIDATION STATUS
-----------------
✅ File is structurally valid with no critical errors.

⚠️  Warning: CLM06 (Provider Signature on File) is missing on Claim #2.
    FIX: Set CLM06 to 'Y' if provider signature is on file, or 'N' if not.
    This field is required by most payers and may cause claim rejection.

ACTION ITEMS
------------
1. Correct the missing CLM06 value on Claim #2 before resubmission
2. Verify all NPI numbers are current and active
3. Submit to payer clearinghouse for processing
4. Expect remittance (835) within 14-30 days
"""


def demo_function_api():
    """Demo using function-based API."""
    print("=" * 70)
    print("Demo 1: Function-Based API")
    print("=" * 70)
    
    # Note: In real usage, you would parse an actual EDI file
    # For this demo, we'll show the API structure
    
    print("\nCode example:")
    print("""
    from validedi import parse, validate
    from validedi.llm import explain, ask_followup
    
    # Parse and validate
    edi_result = parse("file.edi")
    val_result = validate(edi_result)
    
    # Get explanation with your LLM
    result = explain(edi_result, val_result, llm=my_llm)
    print(result.report)
    
    # Ask questions
    answer = ask_followup("What is the total?", edi_result, val_result, llm=my_llm)
    print(answer)
    """)
    
    print("\nWith mock LLM:")
    print("-" * 70)
    
    # Simulate LLM response
    mock_result = mock_llm("explain this EDI file")
    print(mock_result)


def demo_class_api():
    """Demo using class-based API."""
    print("\n" + "=" * 70)
    print("Demo 2: Class-Based API (Reusable)")
    print("=" * 70)
    
    print("\nCode example:")
    print("""
    from validedi.llm import LLMExplainer
    
    # Create reusable explainer
    explainer = LLMExplainer(llm=my_llm)
    
    # Process multiple files
    for filepath in files:
        edi_result = parse(filepath)
        val_result = validate(edi_result)
        
        result = explainer.explain(edi_result, val_result)
        answer = explainer.ask_followup("Any errors?", edi_result, val_result)
    """)
    
    print("\nBenefit: Create once, reuse for multiple files!")


def demo_rule_based():
    """Demo rule-based fallback (no LLM)."""
    print("\n" + "=" * 70)
    print("Demo 3: Rule-Based Fallback (No LLM Required)")
    print("=" * 70)
    
    print("\nCode example:")
    print("""
    from validedi import parse, validate
    from validedi.llm import explain
    
    # Parse and validate
    edi_result = parse("file.edi")
    val_result = validate(edi_result)
    
    # Get explanation WITHOUT LLM
    result = explain(edi_result, val_result)  # No llm parameter!
    print(result.report)
    print(f"Generated by: {result.source}")  # Will show "rule_based"
    """)
    
    print("\nBenefit: Works offline, no API costs, always available!")


def demo_providers():
    """Demo different LLM providers."""
    print("\n" + "=" * 70)
    print("Demo 4: Works with ANY LLM Provider")
    print("=" * 70)
    
    providers = [
        ("OpenAI GPT-4", """
from openai import OpenAI
client = OpenAI(api_key="sk-...")
llm = lambda p: client.chat.completions.create(
    model="gpt-4", messages=[{"role": "user", "content": p}]
).choices[0].message.content
"""),
        ("Groq Llama 3.1", """
from groq import Groq
client = Groq(api_key="gsk_...")
llm = lambda p: client.chat.completions.create(
    model="llama-3.1-70b-versatile", messages=[{"role": "user", "content": p}]
).choices[0].message.content
"""),
        ("AWS Bedrock Claude", """
import boto3, json
bedrock = boto3.client('bedrock-runtime')
def llm(p):
    response = bedrock.invoke_model(
        modelId="anthropic.claude-v2",
        body=json.dumps({"prompt": f"\\n\\nHuman: {p}\\n\\nAssistant:", "max_tokens_to_sample": 1200})
    )
    return json.loads(response['body'].read())['completion']
"""),
        ("Google Gemini", """
import google.generativeai as genai
genai.configure(api_key="...")
model = genai.GenerativeModel('gemini-pro')
llm = lambda p: model.generate_content(p).text
"""),
        ("Anthropic Claude", """
from anthropic import Anthropic
client = Anthropic(api_key="sk-ant-...")
llm = lambda p: client.messages.create(
    model="claude-3-opus-20240229", max_tokens=1200,
    messages=[{"role": "user", "content": p}]
).content[0].text
"""),
    ]
    
    for name, code in providers:
        print(f"\n{name}:")
        print(code)
    
    print("\nAnd many more! Any callable that takes a prompt and returns a response works.")


def demo_chatbot():
    """Demo interactive chatbot."""
    print("\n" + "=" * 70)
    print("Demo 5: Interactive Chatbot")
    print("=" * 70)
    
    print("\nRun the interactive chatbot:")
    print("  python examples/llm_chatbot.py path/to/file.edi")
    
    print("\nExample session:")
    print("""
  You: What is the total billed amount?
  Bot: The total billed amount across all 3 claims is $4,250.00.
  
  You: Are there any errors?
  Bot: There is 1 warning: CLM06 (Provider Signature on File) is missing 
       on Claim #2. This should be set to 'Y' or 'N' before submission.
  
  You: Who is the billing provider?
  Bot: The billing provider is Dr. Jane Smith with NPI 1234567890.
  
  You: quit
  👋 Goodbye!
    """)


def main():
    """Run all demos."""
    print("\n" + "=" * 70)
    print("  ValidEDI LLM Integration Demo")
    print("=" * 70)
    print("\nThis demo shows how to use ValidEDI's LLM-powered explanations.")
    print("The LLM integration is provider-agnostic - use ANY LLM you want!")
    print()
    
    demo_function_api()
    demo_class_api()
    demo_rule_based()
    demo_providers()
    demo_chatbot()
    
    print("\n" + "=" * 70)
    print("  Summary")
    print("=" * 70)
    print("\n✅ Works with ANY LLM provider (OpenAI, Groq, Bedrock, Gemini, etc.)")
    print("✅ Simple interface - just pass a callable function")
    print("✅ Works without LLM using rule-based templates")
    print("✅ Interactive Q&A support")
    print("✅ Plain-English explanations")
    print("✅ Actionable fix suggestions")
    
    print("\n📚 Documentation:")
    print("  • Full guide: docs/LLM_GUIDE.md")
    print("  • Quick start: QUICKSTART.md")
    print("  • Examples: examples/llm_usage.py")
    print("  • Chatbot: examples/llm_chatbot.py")
    
    print("\n🚀 Ready to use! No additional dependencies required.")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    main()
