code_set_id: 'coverage_level_codes'
description: 'HD04 Coverage Level Codes for 834 transactions'
codes:
  'CHD': 'Children Only'
  'DEP': 'Dependents Only'
  'E1D': 'Employee and One Dependent'
  'E2D': 'Employee and Two Dependents'
  'E3D': 'Employee and Three or More Dependents'
  'ECH': 'Employee and Children'
  'EMP': 'Employee Only'
  'ESP': 'Employee and Spouse'
  'FAM': 'Family'
  'IND': 'Individual'
  'SPC': 'Spouse and Children'
  'SPO': 'Spouse Only'
  'TWO': 'Two Party'
