code_set_id: 'date_qualifiers'
description: 'DTP01 Date/Time Qualifier Codes'
codes:
  '096': 'Discharge'
  '097': 'Admission'
  '102': 'Issue'
  '150': 'Service'
  '151': 'Effective Date of Change'
  '291': 'Accident'
  '304': 'Latest Visit or Consultation'
  '307': 'Eligibility Begin'
  '308': 'Eligibility End'
  '314': 'Disability Begin'
  '315': 'Disability End'
  '330': 'Disability'
  '348': 'Benefit Begin'
  '349': 'Benefit End'
  '356': 'Employment Begin'
  '357': 'Employment End'
  '360': 'Initial Treatment'
  '361': 'Last Menstrual Period'
  '382': 'Enrollment Signature Date'
  '383': 'Maintenance Effective Date'
  '385': 'Coordination of Benefits'
  '386': 'Plan Begin'
  '387': 'Plan End'
  '388': 'Benefit Selection'
  '435': 'Admission Date/Hour'
  '439': 'Accident Date/Hour'
  '453': 'Acute Manifestation'
  '454': 'Initial Fee'
  '455': 'Initial Treatment'
  '471': 'Prescription'
  '472': 'Service'
  '484': 'Certification Revision/Recertification'
  '573': 'Certification'
  '607': 'Disability'
