code_set_id: 'relationship_codes'
description: 'INS02 Individual Relationship Codes for 834 transactions'
codes:
  '01': 'Spouse'
  '18': 'Self'
  '19': 'Child'
  '20': 'Employee'
  '21': 'Unknown'
  '29': 'Significant Other'
  '32': 'Mother'
  '33': 'Father'
  '34': 'Other Adult'
  '53': 'Life Partner'
  'G8': 'Other Relationship'
