"""
Property-based tests using Hypothesis for:
1. Tokenizer never raises on arbitrary text.
2. parse(to_segment_text(segments)) round-trips.
3. NPI Luhn accepts exactly the numbers generated by a reference implementation.
"""

from __future__ import annotations

from hypothesis import given, settings, strategies as st

from validedi.engine.detector import DelimiterSet
from validedi.engine.tokenizer import tokenize
from validedi.handlers.npi import luhn_check
from app.adapters import parse_edi_content, to_segment_text
from app.models import Segment as AppSegment


# ── Reference NPI Generator ──────────────────────────────────────────────────


def generate_reference_npi(nine_digits: str) -> str:
    """
    CMS 10-digit NPI reference generator.
    Prefixes '80840' + 9 digits, computes the 10th Luhn check digit.
    """
    assert len(nine_digits) == 9 and nine_digits.isdigit()
    full_prefix = "80840" + nine_digits  # 14 digits
    total = 0
    # In a 15-digit number, position from right (1-indexed) is 15 - idx.
    # Check digit is at index 14 (position 1, odd -> not doubled).
    for idx, char in enumerate(full_prefix):
        pos_from_right = 15 - idx
        digit = int(char)
        if pos_from_right % 2 == 0:
            digit *= 2
            if digit > 9:
                digit -= 9
        total += digit

    check_digit = (10 - (total % 10)) % 10
    return nine_digits + str(check_digit)


# ── Property 1: Tokenizer Never Raises on Arbitrary Text ─────────────────────


@settings(max_examples=100, deadline=None)
@given(
    text=st.text(),
    elem_sep=st.sampled_from(["*", "|", "#", "^"]),
    seg_sep=st.sampled_from(["~", "\n", ";", "!"]),
    sub_sep=st.sampled_from([":", ">", "<", "/"]),
)
def test_tokenizer_never_raises_on_arbitrary_text(
    text: str, elem_sep: str, seg_sep: str, sub_sep: str
):
    """Assert tokenizer handles any arbitrary unicode text without crashing."""
    if elem_sep == seg_sep or elem_sep == sub_sep or seg_sep == sub_sep:
        return
    delims = DelimiterSet(
        element_sep=elem_sep,
        segment_sep=seg_sep,
        sub_sep=sub_sep,
        transaction_type="837p",
    )
    result = tokenize(text, delims)
    assert isinstance(result, list)


# ── Property 2: parse(to_segment_text(segments)) Round-Trips ────────────────


safe_seg_id = st.text(
    alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", min_size=2, max_size=3
)
safe_elem_str = st.text(
    alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 -_",
    min_size=0,
    max_size=30,
)


@st.composite
def valid_envelope_segments(draw):
    """Generate minimal valid ISA, GS, ST, custom inner, SE, GE, IEA segments."""
    ctrl = "000000001"
    isa_elements = [
        "00", "          ", "00", "          ",
        "ZZ", "SENDER123456789", "ZZ", "RECEIVER1234567",
        "230101", "1200", "^", "00501", ctrl, "0", "P", ":"
    ]
    isa = AppSegment(id="ISA", elements=isa_elements, line_number=1)
    gs = AppSegment(id="GS", elements=["HC", "SENDER", "RECEIVER", "20230101", "1200", "1", "X", "005010X222A1"], line_number=2)
    st_seg = AppSegment(id="ST", elements=["837", "0001", "005010X222A1"], line_number=3)
    bht = AppSegment(id="BHT", elements=["0019", "00", "REF01", "20230101", "1200", "CH"], line_number=4)

    # Draw 1 to 5 random inner safe segments
    num_inner = draw(st.integers(min_value=1, max_value=5))
    inner = []
    for i in range(num_inner):
        s_id = draw(safe_seg_id)
        if s_id in {"ISA", "GS", "ST", "SE", "GE", "IEA"}:
            s_id = "REF"
        elems = draw(st.lists(safe_elem_str, min_size=1, max_size=4))
        inner.append(AppSegment(id=s_id, elements=elems, line_number=5 + i))

    tx_count = str(len(inner) + 3)
    se = AppSegment(id="SE", elements=[tx_count, "0001"], line_number=5 + len(inner))
    ge = AppSegment(id="GE", elements=["1", "1"], line_number=6 + len(inner))
    iea = AppSegment(id="IEA", elements=["1", ctrl], line_number=7 + len(inner))

    return [isa, gs, st_seg, bht] + inner + [se, ge, iea]


@settings(max_examples=50, deadline=None)
@given(segments=valid_envelope_segments())
def test_parse_to_segment_text_roundtrip(segments: list[AppSegment]):
    """Assert parse(to_segment_text(segments)) accurately round-trips segment IDs and elements."""
    text = to_segment_text(segments, element_sep="*", segment_sep="~")
    parsed = parse_edi_content(text)

    # Every original segment must match parsed segment id and non-padded elements
    assert len(parsed.segments) == len(segments)
    for orig, roundtripped in zip(segments, parsed.segments):
        assert orig.id == roundtripped.id
        if orig.id != "ISA":
            assert len(orig.elements) == len(roundtripped.elements)
            for e_orig, e_rt in zip(orig.elements, roundtripped.elements):
                assert e_orig.strip() == e_rt.strip()


# ── Property 3: NPI Luhn Accepts Exactly Numbers from Reference ─────────────


@settings(max_examples=100, deadline=None)
@given(nine_digits=st.text(alphabet="0123456789", min_size=9, max_size=9))
def test_npi_luhn_accepts_exactly_reference_numbers(nine_digits: str):
    """
    Assert NPI Luhn accepts exactly the numbers produced by the reference generator,
    and rejects any digit modification.
    """
    valid_npi = generate_reference_npi(nine_digits)

    # Must accept the reference number
    assert luhn_check(valid_npi) is True

    # Mutating the check digit must always fail
    correct_check = int(valid_npi[-1])
    for wrong_digit in range(10):
        if wrong_digit != correct_check:
            wrong_npi = nine_digits + str(wrong_digit)
            assert luhn_check(wrong_npi) is False
