"""
ValidEDI LLM Usage Examples
============================

This example demonstrates how to use ValidEDI's LLM-powered explanations
with various LLM providers.

The LLM integration is provider-agnostic - you can use any LLM that accepts
a prompt string and returns a response string.
"""

from validedi import parse, validate
from validedi.llm import explain, ask_followup, LLMExplainer


# ══════════════════════════════════════════════════════════════════════════════
# Example 1: Using OpenAI GPT-4
# ══════════════════════════════════════════════════════════════════════════════

def example_openai():
    """Example using OpenAI's GPT-4."""
    print("=" * 70)
    print("Example 1: OpenAI GPT-4")
    print("=" * 70)
    
    try:
        from openai import OpenAI
        
        # Initialize OpenAI client
        client = OpenAI(api_key="your-api-key-here")
        
        # Create LLM callable
        def llm(prompt: str) -> str:
            response = client.chat.completions.create(
                model="gpt-4",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3,
                max_tokens=1200
            )
            return response.choices[0].message.content
        
        # Parse and validate EDI file
        edi_result = parse("path/to/your/file.edi")
        val_result = validate(edi_result)
        
        # Get explanation
        result = explain(edi_result, val_result, llm=llm)
        print(result.report)
        print(f"\nGenerated by: {result.source}")
        
        # Ask follow-up questions
        answer = ask_followup(
            "What is the total billed amount?",
            edi_result,
            val_result,
            llm=llm
        )
        print(f"\nQ&A: {answer}")
        
    except ImportError:
        print("❌ OpenAI package not installed. Install with: pip install openai")
    except Exception as e:
        print(f"❌ Error: {e}")


# ══════════════════════════════════════════════════════════════════════════════
# Example 2: Using Groq (Fast, Free Tier Available)
# ══════════════════════════════════════════════════════════════════════════════

def example_groq():
    """Example using Groq's Llama 3.1."""
    print("\n" + "=" * 70)
    print("Example 2: Groq Llama 3.1")
    print("=" * 70)
    
    try:
        from groq import Groq
        
        # Initialize Groq client
        client = Groq(api_key="your-groq-api-key")
        
        # Create LLM callable
        def llm(prompt: str) -> str:
            response = client.chat.completions.create(
                model="llama-3.1-70b-versatile",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3,
                max_tokens=1200
            )
            return response.choices[0].message.content
        
        # Parse and validate
        edi_result = parse("path/to/your/file.edi")
        val_result = validate(edi_result)
        
        # Get explanation
        result = explain(edi_result, val_result, llm=llm)
        print(result.report)
        
    except ImportError:
        print("❌ Groq package not installed. Install with: pip install groq")
    except Exception as e:
        print(f"❌ Error: {e}")


# ══════════════════════════════════════════════════════════════════════════════
# Example 3: Using AWS Bedrock
# ══════════════════════════════════════════════════════════════════════════════

def example_bedrock():
    """Example using AWS Bedrock with Claude."""
    print("\n" + "=" * 70)
    print("Example 3: AWS Bedrock (Claude)")
    print("=" * 70)
    
    try:
        import boto3
        import json
        
        # Initialize Bedrock client
        bedrock = boto3.client(
            service_name='bedrock-runtime',
            region_name='us-east-1'
        )
        
        # Create LLM callable
        def llm(prompt: str) -> str:
            body = json.dumps({
                "prompt": f"\n\nHuman: {prompt}\n\nAssistant:",
                "max_tokens_to_sample": 1200,
                "temperature": 0.3,
            })
            
            response = bedrock.invoke_model(
                modelId="anthropic.claude-v2",
                body=body
            )
            
            response_body = json.loads(response['body'].read())
            return response_body['completion']
        
        # Parse and validate
        edi_result = parse("path/to/your/file.edi")
        val_result = validate(edi_result)
        
        # Get explanation
        result = explain(edi_result, val_result, llm=llm)
        print(result.report)
        
    except ImportError:
        print("❌ boto3 not installed. Install with: pip install boto3")
    except Exception as e:
        print(f"❌ Error: {e}")


# ══════════════════════════════════════════════════════════════════════════════
# Example 4: Using Google Gemini
# ══════════════════════════════════════════════════════════════════════════════

def example_gemini():
    """Example using Google Gemini."""
    print("\n" + "=" * 70)
    print("Example 4: Google Gemini")
    print("=" * 70)
    
    try:
        import google.generativeai as genai
        
        # Configure Gemini
        genai.configure(api_key="your-google-api-key")
        model = genai.GenerativeModel('gemini-pro')
        
        # Create LLM callable
        def llm(prompt: str) -> str:
            response = model.generate_content(prompt)
            return response.text
        
        # Parse and validate
        edi_result = parse("path/to/your/file.edi")
        val_result = validate(edi_result)
        
        # Get explanation
        result = explain(edi_result, val_result, llm=llm)
        print(result.report)
        
    except ImportError:
        print("❌ google-generativeai not installed. Install with: pip install google-generativeai")
    except Exception as e:
        print(f"❌ Error: {e}")


# ══════════════════════════════════════════════════════════════════════════════
# Example 5: Using Anthropic Claude
# ══════════════════════════════════════════════════════════════════════════════

def example_anthropic():
    """Example using Anthropic Claude."""
    print("\n" + "=" * 70)
    print("Example 5: Anthropic Claude")
    print("=" * 70)
    
    try:
        from anthropic import Anthropic
        
        # Initialize Anthropic client
        client = Anthropic(api_key="your-anthropic-api-key")
        
        # Create LLM callable
        def llm(prompt: str) -> str:
            response = client.messages.create(
                model="claude-3-opus-20240229",
                max_tokens=1200,
                temperature=0.3,
                messages=[{"role": "user", "content": prompt}]
            )
            return response.content[0].text
        
        # Parse and validate
        edi_result = parse("path/to/your/file.edi")
        val_result = validate(edi_result)
        
        # Get explanation
        result = explain(edi_result, val_result, llm=llm)
        print(result.report)
        
    except ImportError:
        print("❌ anthropic package not installed. Install with: pip install anthropic")
    except Exception as e:
        print(f"❌ Error: {e}")


# ══════════════════════════════════════════════════════════════════════════════
# Example 6: Without LLM (Rule-Based Fallback)
# ══════════════════════════════════════════════════════════════════════════════

def example_rule_based():
    """Example using rule-based templates (no LLM required)."""
    print("\n" + "=" * 70)
    print("Example 6: Rule-Based (No LLM)")
    print("=" * 70)
    
    # Parse and validate
    edi_result = parse("path/to/your/file.edi")
    val_result = validate(edi_result)
    
    # Get explanation without LLM
    result = explain(edi_result, val_result)  # No llm parameter
    print(result.report)
    print(f"\nGenerated by: {result.source}")


# ══════════════════════════════════════════════════════════════════════════════
# Example 7: Using Class-Based API
# ══════════════════════════════════════════════════════════════════════════════

def example_class_based():
    """Example using the class-based API for reusable explainer."""
    print("\n" + "=" * 70)
    print("Example 7: Class-Based API")
    print("=" * 70)
    
    try:
        from openai import OpenAI
        
        # Initialize OpenAI
        client = OpenAI(api_key="your-api-key-here")
        
        def llm(prompt: str) -> str:
            response = client.chat.completions.create(
                model="gpt-4",
                messages=[{"role": "user", "content": prompt}]
            )
            return response.choices[0].message.content
        
        # Create reusable explainer
        explainer = LLMExplainer(llm=llm)
        
        # Process multiple files
        files = ["file1.edi", "file2.edi", "file3.edi"]
        
        for filepath in files:
            edi_result = parse(filepath)
            val_result = validate(edi_result)
            
            # Get explanation
            result = explainer.explain(edi_result, val_result)
            print(f"\n{filepath}:")
            print(result.report[:200] + "...")  # Print first 200 chars
            
            # Ask questions
            answer = explainer.ask_followup(
                "Are there any critical errors?",
                edi_result,
                val_result
            )
            print(f"Q&A: {answer}")
        
    except ImportError:
        print("❌ OpenAI package not installed")
    except Exception as e:
        print(f"❌ Error: {e}")


# ══════════════════════════════════════════════════════════════════════════════
# Example 8: Custom LLM Wrapper
# ══════════════════════════════════════════════════════════════════════════════

def example_custom_wrapper():
    """Example with custom LLM wrapper for logging/monitoring."""
    print("\n" + "=" * 70)
    print("Example 8: Custom LLM Wrapper")
    print("=" * 70)
    
    class MonitoredLLM:
        """Custom LLM wrapper with logging and error handling."""
        
        def __init__(self, base_llm):
            self.base_llm = base_llm
            self.call_count = 0
            self.total_tokens = 0
        
        def __call__(self, prompt: str) -> str:
            self.call_count += 1
            print(f"📞 LLM Call #{self.call_count}")
            print(f"📝 Prompt length: {len(prompt)} chars")
            
            try:
                response = self.base_llm(prompt)
                print(f"✅ Response length: {len(response)} chars")
                return response
            except Exception as e:
                print(f"❌ LLM Error: {e}")
                raise
    
    # Example with mock LLM
    def mock_llm(prompt: str) -> str:
        return "This is a mock LLM response for testing."
    
    # Wrap it
    monitored_llm = MonitoredLLM(mock_llm)
    
    # Use it
    edi_result = parse("path/to/your/file.edi")
    val_result = validate(edi_result)
    
    result = explain(edi_result, val_result, llm=monitored_llm)
    print(f"\nTotal LLM calls: {monitored_llm.call_count}")


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("ValidEDI LLM Usage Examples")
    print("=" * 70)
    print("\nThese examples show how to use ValidEDI with various LLM providers.")
    print("Uncomment the example you want to run and add your API keys.\n")
    
    # Uncomment the example you want to run:
    
    # example_openai()
    # example_groq()
    # example_bedrock()
    # example_gemini()
    # example_anthropic()
    example_rule_based()  # This one works without any setup
    # example_class_based()
    # example_custom_wrapper()
